export type DaemonRequest = {
  id: string
  verb: string
  args: string[]
  /**
   * Per-daemon auth token (32-byte hex, 64 chars). Required on every request.
   * Generated by the daemon at startup and written to the handshake file
   * alongside `url`. Without a valid token the daemon rejects the request —
   * prevents any other local process on a multi-user system (or any other
   * process running as your user) from driving the browser by POSTing to
   * the daemon's HTTP endpoint.
   */
  auth?: string
}

export type DaemonResponse = {
  id: string
  ok: boolean
  envelope: Record<string, unknown>
  message?: string
}

export type DaemonLifecycleResponse = {
  id: string
  ok: boolean
  message?: string
}

export type DaemonHandshake = {
  pid: number
  version: string
  startedAt: number
  idleTimeoutMs: number
  sessionID: string
  /**
   * Base URL of the per-session HTTP endpoint, e.g. `http://127.0.0.1:54321`.
   * Single source of truth — clients POST to `${url}/call` and need not
   * reconstruct host/port themselves.
   */
  url: string
  /**
   * Per-daemon auth token. Clients must echo this on every request.
   * See `DaemonRequest.auth`.
   */
  token: string
}
